pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                dir('django_web_app'){
                    sh "docker build -t batchen-jenkins:0.1.0 ."
                    sh "docker images"
                }
            }
        }
    }
    post {
        // always {
        //     deleteDir() /* clean up our workspace */
        // }
        success {
            echo 'build succeeded!'
        }
        failure {
            echo 'the pipeline failed :('
        }
    }
}

