pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                dir('django_web_app'){
                    sh "docker build -t batchen-jenkins:0.1.0 ."
                    sh "docker images"
                }
            }
        }
        stage('Test') {
            steps {
                dir('django_web_app'){
                    //sh "chmod +x manage.py"
                    //sh 'pip install -r requirements.txt'
                    //sh "python ./manage.py test"
                }
            }
        }
    }
    post {
        always {
            deleteDir() 
        }
        success {
            echo 'build succeeded!'
        }
        failure {
            echo 'the pipeline failed :('
        }
    }
}

