pipeline {
    agent any 

    // environment {
    //     PATH = "${tool 'Python3'}/bin:${env.PATH}"
    // }
    stages {
        stage('Build') {
            steps {
                dir('django_web_app'){
                    sh "docker rmi $(docker images -q)"
                    sh "docker build -t batchen-jenkins:0.1.0 ."
                    sh "docker images"
                }
            }
        }
        stage('Test') {
            steps {
                dir('django_web_app'){
                    //sh "sudo apt-get install -y python3"
                    //sh "chmod +x manage.py"
                    sh "python3 -m venv .venv"
                    //sh "source .venv/bin/activate"
                    sh "python3 -m pip install -r requirements.txt"
                    sh "python3 ./manage.py test"
                }
            }
        }
    }
    post {
        always {
            deleteDir() 
        }
        success {
            echo 'build succeeded!'
        }
        failure {
            echo 'the pipeline failed :('
        }
    }
}

